name: Main Pipeline Router

on:
  push:
    branches:
      - dev
      - uat
      - prod
    paths-ignore:
      - 'k8s/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  router:
    runs-on: ubuntu-latest
    steps:
      - name: Display Route Info
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "Triggering corresponding environment pipeline..."

  dev-pipeline:
    needs: router
    if: github.ref_name == 'dev'
    uses: ./.github/workflows/dev.yml
    secrets: inherit

  uat-pipeline:
    needs: router
    if: github.ref_name == 'uat'
    uses: ./.github/workflows/uat.yml
    secrets: inherit

  prod-pipeline:
    needs: router
    if: github.ref_name == 'prod'
    uses: ./.github/workflows/prod.yml
    secrets: inherit
